# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  instance-management-service:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    environment:
      EdFi_AdminConsole_AppSettings__DatabaseEngine: ${DATABASE_ENGINE:-PostgreSQL}
      EdFi_AdminConsole_AppSettings__PathBase: ${PATHBASE:-""}
      EdFi_AdminConsole_AppSettings__DefaultPageSizeOffset: 0
      EdFi_AdminConsole_AppSettings__DefaultPageSizeLimit: 25
      EdFi_AdminConsole_AppSettings__OverrideExistingDatabase: ${OVERRIDE_EXISTING_DATABASE:-false}
      EdFi_AdminConsole_AppSettings__IgnoresCertificateErrors: ${IGNORES_CERTIFICATE_ERRORS:-true}
      EdFi_AdminConsole_ConnectionStrings__EdFi_Master: ${EDFI_MASTER:-host=host.docker.internal;port=5432;username=postgres;password=admin;database=postgres;pooling=false}
      EdFi_AdminConsole_ConnectionStrings__EdFi_Ods: ${EDFI_ODS:-host=host.docker.internal;port=5432;username=postgres;password=admin;database={0};pooling=false}
      EdFi_AdminConsole_AdminApiSettings__AccessTokenUrl: ${ACCESS_TOKEN_URL:-https://host.docker.internal/auth/realms/edfi-admin-console/protocol/openid-connect/token}
      EdFi_AdminConsole_AdminApiSettings__AdminConsoleTenantsURL: ${ADMINCONSOLE_TENANTS_URL:-https://host.docker.internal/adminapi/adminconsole/tenants}
      EdFi_AdminConsole_AdminApiSettings__AdminConsoleInstancesURL: ${ADMINCONSOLE_INSTANCES_URL:-https://host.docker.internal/adminapi/adminconsole/instances?status={0}}
      EdFi_AdminConsole_AdminApiSettings__AdminConsoleCompleteInstancesURL: ${ADMINCONSOLE_COMPLETE_INSTANCES_URL:-https://host.docker.internal/adminapi/adminconsole/instances/{0}/completed}
      EdFi_AdminConsole_AdminApiSettings__Username: ${USERNAME:-adminconsole-user}
      EdFi_AdminConsole_AdminApiSettings__ClientId: ${CLIENTID:-admin-console}
      EdFi_AdminConsole_AdminApiSettings__Password: ${PASSWORD:-SomePassword}
      EdFi_AdminConsole_DatabaseProvider: ${DATABASE_PROVIDER:-Npgsql} 
    volumes:
      - service-logs:/var/log/acinstancesvc
  
  pg-service:
    container_name: pg-13-alpine
    image: postgres:13-alpine
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "postgres"
      PG_PORT: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
       
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pg-service
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
 
volumes:
  postgres-data:
    name: postgres-data
  service-logs:
    name: instance-management-service-logs
